## Simple Problem

In [3]:
import numpy as np
import matplotlib.pyplot as plt
from fastncut import FastNcut

# all element be same value
const = np.array([[0,1],[0,2]])
A = np.array([[2, 0, 0],[0, 1, 0],[0, 0, 0]])
model  = FastNcut(const=const)
model.fit(A)

1th element  and 2th element be same value in the eigen vector.
1th element  and 3th element be same value in the eigen vector.
***Projected Power Method***
 Iteration : 1 residual : 4.5352842082615314
 Iteration : 2 residual : 0.5731493718290084
 Iteration : 3 residual : 1.7763568394002505e-15
constrained eigen vector : 
 [[ 1.34164079]
 [ 1.34164079]
 [ 1.34164079]]


In [4]:
# all element be same value
const = np.array([[0,1]])
model  = FastNcut(const=const)
model.fit(A)

1th element  and 2th element be same value in the eigen vector.
***Projected Power Method***
 Iteration : 1 residual : 2.6184412278082867
 Iteration : 2 residual : 1.026379510489444
 Iteration : 3 residual : 0.0
constrained eigen vector : 
 [[ 1.34164079]
 [ 1.34164079]
 [ 0.        ]]


In [5]:
# all element be same value
const = np.array([[0,2]])
model  = FastNcut(const=const)
model.fit(A)

1th element  and 3th element be same value in the eigen vector.
***Projected Power Method***
 Iteration : 1 residual : 0.2514317567456148
 Iteration : 2 residual : 0.0
constrained eigen vector : 
 [[ 0.21048959]
 [ 0.9775961 ]
 [ 0.21048959]]


In [27]:
np.zeros([3,1])

array([[ 0.],
       [ 0.],
       [ 0.]])

In [7]:
a,b = 1,2

In [8]:
a

1

In [9]:
b

2

In [10]:
a,b = [0,1]

In [11]:
a

0

In [12]:
b

1